language: node_js
node_js:
- '0.11'
- '0.10'
before_install:
- npm install -g grunt-cli
addons:
  sauce_connect: true
env:
  global:
  - secure: gKeJflsQYPZdSskc86z9fLMEcIY6QbwaiuHYKqIL1gM0HfokZdiEAfKt2SmYE3kpfRmtwJWxDHTQ3h34G+xMYxDbH6o8Rq5rsGWtWNypBaNskPfi1244/K30rnxTV/5RamWa0nQVTiQYSYy7828zCOG1thnHjOfMhsguIthdRJY=
  - secure: btiGl1DXk2obEQjjC4sywQK2HpV9WWYbo6j4HaE1KE37dz7yr8ChOUF1dFIDwZCyepnTHM1L2EX+SS5p5zfOXqauYXhpDl9CS0FD5IcBz9YVxKies3Q0F8UpjHmbQN+lzIjkHMK4IPXp7nkjsb4jX5vdxgxCcy5lhXB0aS/TPdk=
